/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedScanRouteImport } from './routes/_authenticated/scan'
import { Route as AuthenticatedReportRouteImport } from './routes/_authenticated/report'
import { Route as AuthenticatedQrPrintRouteImport } from './routes/_authenticated/qr-print'
import { Route as AuthenticatedArrearsRouteImport } from './routes/_authenticated/arrears'
import { Route as AuthenticatedCustomersIndexRouteImport } from './routes/_authenticated/customers.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedCustomersNewRouteImport } from './routes/_authenticated/customers.new'
import { Route as AuthenticatedCustomersIdRouteImport } from './routes/_authenticated/customers.$id'
import { Route as AuthenticatedAdminLoginLogsRouteImport } from './routes/_authenticated/admin.login-logs'
import { Route as AuthenticatedAdminAccountRouteImport } from './routes/_authenticated/admin.account'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScanRoute = AuthenticatedScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportRoute = AuthenticatedReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQrPrintRoute = AuthenticatedQrPrintRouteImport.update({
  id: '/qr-print',
  path: '/qr-print',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedArrearsRoute = AuthenticatedArrearsRouteImport.update({
  id: '/arrears',
  path: '/arrears',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustomersIndexRoute =
  AuthenticatedCustomersIndexRouteImport.update({
    id: '/customers/',
    path: '/customers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustomersNewRoute =
  AuthenticatedCustomersNewRouteImport.update({
    id: '/customers/new',
    path: '/customers/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCustomersIdRoute =
  AuthenticatedCustomersIdRouteImport.update({
    id: '/customers/$id',
    path: '/customers/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminLoginLogsRoute =
  AuthenticatedAdminLoginLogsRouteImport.update({
    id: '/admin/login-logs',
    path: '/admin/login-logs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAccountRoute =
  AuthenticatedAdminAccountRouteImport.update({
    id: '/admin/account',
    path: '/admin/account',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/arrears': typeof AuthenticatedArrearsRoute
  '/qr-print': typeof AuthenticatedQrPrintRoute
  '/report': typeof AuthenticatedReportRoute
  '/scan': typeof AuthenticatedScanRoute
  '/admin/account': typeof AuthenticatedAdminAccountRoute
  '/admin/login-logs': typeof AuthenticatedAdminLoginLogsRoute
  '/customers/$id': typeof AuthenticatedCustomersIdRoute
  '/customers/new': typeof AuthenticatedCustomersNewRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/customers/': typeof AuthenticatedCustomersIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/arrears': typeof AuthenticatedArrearsRoute
  '/qr-print': typeof AuthenticatedQrPrintRoute
  '/report': typeof AuthenticatedReportRoute
  '/scan': typeof AuthenticatedScanRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/account': typeof AuthenticatedAdminAccountRoute
  '/admin/login-logs': typeof AuthenticatedAdminLoginLogsRoute
  '/customers/$id': typeof AuthenticatedCustomersIdRoute
  '/customers/new': typeof AuthenticatedCustomersNewRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/customers': typeof AuthenticatedCustomersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/arrears': typeof AuthenticatedArrearsRoute
  '/_authenticated/qr-print': typeof AuthenticatedQrPrintRoute
  '/_authenticated/report': typeof AuthenticatedReportRoute
  '/_authenticated/scan': typeof AuthenticatedScanRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/account': typeof AuthenticatedAdminAccountRoute
  '/_authenticated/admin/login-logs': typeof AuthenticatedAdminLoginLogsRoute
  '/_authenticated/customers/$id': typeof AuthenticatedCustomersIdRoute
  '/_authenticated/customers/new': typeof AuthenticatedCustomersNewRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/customers/': typeof AuthenticatedCustomersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/arrears'
    | '/qr-print'
    | '/report'
    | '/scan'
    | '/admin/account'
    | '/admin/login-logs'
    | '/customers/$id'
    | '/customers/new'
    | '/admin/'
    | '/customers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/arrears'
    | '/qr-print'
    | '/report'
    | '/scan'
    | '/'
    | '/admin/account'
    | '/admin/login-logs'
    | '/customers/$id'
    | '/customers/new'
    | '/admin'
    | '/customers'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/arrears'
    | '/_authenticated/qr-print'
    | '/_authenticated/report'
    | '/_authenticated/scan'
    | '/_authenticated/'
    | '/_authenticated/admin/account'
    | '/_authenticated/admin/login-logs'
    | '/_authenticated/customers/$id'
    | '/_authenticated/customers/new'
    | '/_authenticated/admin/'
    | '/_authenticated/customers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scan': {
      id: '/_authenticated/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof AuthenticatedScanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/report': {
      id: '/_authenticated/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof AuthenticatedReportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/qr-print': {
      id: '/_authenticated/qr-print'
      path: '/qr-print'
      fullPath: '/qr-print'
      preLoaderRoute: typeof AuthenticatedQrPrintRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/arrears': {
      id: '/_authenticated/arrears'
      path: '/arrears'
      fullPath: '/arrears'
      preLoaderRoute: typeof AuthenticatedArrearsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers/': {
      id: '/_authenticated/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof AuthenticatedCustomersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers/new': {
      id: '/_authenticated/customers/new'
      path: '/customers/new'
      fullPath: '/customers/new'
      preLoaderRoute: typeof AuthenticatedCustomersNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers/$id': {
      id: '/_authenticated/customers/$id'
      path: '/customers/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof AuthenticatedCustomersIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/login-logs': {
      id: '/_authenticated/admin/login-logs'
      path: '/admin/login-logs'
      fullPath: '/admin/login-logs'
      preLoaderRoute: typeof AuthenticatedAdminLoginLogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/account': {
      id: '/_authenticated/admin/account'
      path: '/admin/account'
      fullPath: '/admin/account'
      preLoaderRoute: typeof AuthenticatedAdminAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedArrearsRoute: typeof AuthenticatedArrearsRoute
  AuthenticatedQrPrintRoute: typeof AuthenticatedQrPrintRoute
  AuthenticatedReportRoute: typeof AuthenticatedReportRoute
  AuthenticatedScanRoute: typeof AuthenticatedScanRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAdminAccountRoute: typeof AuthenticatedAdminAccountRoute
  AuthenticatedAdminLoginLogsRoute: typeof AuthenticatedAdminLoginLogsRoute
  AuthenticatedCustomersIdRoute: typeof AuthenticatedCustomersIdRoute
  AuthenticatedCustomersNewRoute: typeof AuthenticatedCustomersNewRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedCustomersIndexRoute: typeof AuthenticatedCustomersIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedArrearsRoute: AuthenticatedArrearsRoute,
  AuthenticatedQrPrintRoute: AuthenticatedQrPrintRoute,
  AuthenticatedReportRoute: AuthenticatedReportRoute,
  AuthenticatedScanRoute: AuthenticatedScanRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAdminAccountRoute: AuthenticatedAdminAccountRoute,
  AuthenticatedAdminLoginLogsRoute: AuthenticatedAdminLoginLogsRoute,
  AuthenticatedCustomersIdRoute: AuthenticatedCustomersIdRoute,
  AuthenticatedCustomersNewRoute: AuthenticatedCustomersNewRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedCustomersIndexRoute: AuthenticatedCustomersIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
